language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
before_script:
  - psql -c "create database spyne_test_$USER;" -U postgres
before_install:
  - sudo apt-get install -qq libzmq3-dev
install:
  - python setup.py develop
  - pip install tox
script:
  # Temporary solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]]; then bash -c "python setup.py install_test_deps; python setup.py install_test_deps; exit 0"; fi
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]]; then python setup.py test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then tox -e py33; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then tox -e pypy; fi
